### ISSUE TITLE
add-on builder shouldn't force arch in config.json

### ISSUE THREAD

**Issue by korylprince** [home-assistant/hassio-build#148]
According to the docs, the add-on `config.json` `arch` key is: 

> List of supported arch: armhf, aarch64, amd64, i386. **Default all**.

However with the changes made in 72986efb1dc98a9055870c418d89e13f77c46885 (specifically [this section](https://github.com/home-assistant/hassio-build/commit/72986efb1dc98a9055870c418d89e13f77c46885#diff-a6c37226e7494cb81489aa3d75f7aa39R327)), the builder refuses to build any arch for an add-on that does not have the `arch` key in `config.json` with the message: `[ERROR] $ARCH not supported for this add-on`.

This differs from the old (and IMO correct) behavior of allowing builds of all archs when the `arch` key is missing.

**Comment by frenck** [comment]
The arch key should be enforced, since not having it, will cause troubles when adding new ones.
e.g., the recently added `armv7` causes issues, since a lot of add-ons do not have the supported arch listed, hence Hass.io assumes it supports all (including the new `armv7`).

So, please, just specify the supported arches by your add-on.

**Comment by korylprince** [comment]
Works for me. I've updated my add-ons, and I see the docs have already been updated in master.
